### ISSUE TITLE
Selenium RC page blank

### ISSUE THREAD

**Issue by hazmeister** [SeleniumHQ/docs#108]
The [Selenium RC](https://seleniumhq.github.io/docs/rc.html) page is blank.  We ought to cover the basics here, with a small recommendation anyone starting fresh to use WebDriver.

**Comment by lukeis** [comment]
it's been deprecated and removed. Linking to the current www.seleniumhq.org docs would be about as much information as needed (with the suggestion to use WebDriver instead)

**Comment by andreastt** [comment]
Rewrite of documentation is a WIP.

**Comment by hazmeister** [comment]
@lukeis if these docs are intended to replace the docs on the main site, do we need to mirror that info here?  Or should we reduce the mentions of RC and get rid of the page I linked?

**Comment by andreastt** [comment]
We should mention somewhere that RC was a thing of Selenium 2 and that it is going away. In my opinion we should not mirror the existing RC documentation or write new documentation on RC, as it is a thing we want to go away.

I guess what I’m saying here implies we should get rid of the page you linked.

**Comment by hazmeister** [comment]
Thanks @andreastt , I'll raise a PR.
