### ISSUE TITLE
Migrating from RC to WebDriver Page Blank

### ISSUE THREAD

**Issue by hazmeister** [SeleniumHQ/docs#109]
The [SELENIUM REMOTE CONTROL TO WEBDRIVER MIGRATION](https://seleniumhq.github.io/docs/rctowd.html) page is blank.

Looking for some additional hints and tips to write this up - I'll be starting with:
[Migrating the herd - How Salesforce is migrating 35,000 Selenium RC tests @ Selenium Conf 14](https://www.youtube.com/watch?v=qrQaCVuJCV8)

**Comment by andreastt** [comment]
This documentation is a WIP.
