### ISSUE TITLE
Grammatical issues

### ISSUE THREAD

**Issue by User135249** [SeleniumHQ/docs#113]
Here are some links to pages and grammatical issues that are on them:

[Page 1](https://seleniumhq.github.io/docs/wd.html):
     1. Under "DRIVER REQUIREMENTS":
          (a) In the 2nd paragraph, there's "detalis".
          (b) Under "Chromium/Chrome": in the 2nd paragraph, "that makes up" needs to be changed to "make up".
          (c) Under "Opera (Presto-based)": in the 1st paragraph, there needs to be a period after "server JAR".
     2. Under "WAITS" -> "Explicit waiting":
          (a) In the last sentence of the 1st paragraph:
               -There's "falsy".
               -The 2nd occurrence of "keep" needs to be removed.
          (b) In the 1st sentence of the 4th paragraph, there's "truthy".

[Page 2](https://seleniumhq.github.io/docs/grid.html)
     1. Under "PROS AND CONS": in the first paragraph, "suite" needs to be changed to "suit".
     2. Under "ROLLING YOUR OWN GRID": under "Quick start", there's the following line:
               "Step 1: Start the ub"

**Comment by maeriens** [comment]
I have all the files changed to make a pull request for this issue; however I do not believe that 2.a ('Falsy') nor 2.b ('Truthy') are wrong (There is even an [article about Falsy in MDN](https://developer.mozilla.org/en-US/docs/Glossary/Falsy); and the [same goes for Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)).

**Comment by ddavison** [comment]
closed in #114
