### ISSUE TITLE
Install Page typos

### ISSUE THREAD

**Issue by maeriens** [SeleniumHQ/docs#115]
1. Add `<code class=xml>` to XML example snippets.
2. Text > SELENIUM INSTALLATION:  _depends on browsers you want to run your [...]_  > add 'the' before 'browsers'
3. Text > USING BROWSER SPECIFIC JAR: _run tests in only a specific browser_ > swap 'in' and 'only'
4. Text > USING BROWSER SPECIFIC JAR: Rephrase to reflect that Firefox is not mandatory (Add 'for example').
5. Text: Remove _That's all and you are ready to driver your tests in Firefox._ line; as it does not add value and the sentence that follows it about Chrome is more important.
6. Text: _In *a* similar manner_
7. Text: Slightly rephrase Chrome's capability sentence to be similar to Firefox's one.
8. Text: The link to download the _selenium-server-standalone JAR_ does not redirect correctly due to it having _https_ at the beginning of it.
9. Text: Capitalize 'Selenium' in _selenium-server-standalone jar is never uploaded,[...]_, under *USING STANDALONE JAR*.

**Comment by maeriens** [comment]
@andreastt is this still relevant?

**Comment by andreastt** [comment]
Sure, but the PR has conflicts and merge commits on it.

**Comment by maeriens** [comment]
I think it's done 👍

**Comment by diemol** [comment]
Closed via #116
