### ISSUE TITLE
Move to Jekyll

### ISSUE THREAD

**Issue by MartinDelille** [SeleniumHQ/docs#119]
I was wondering if you would be interested to move to [Jekyll](https://jekyllrb.com) since it's natively supported by *Github Pages*. It would make easier the redaction of new articles and future maintenance of the site.

Tell me if you're interested so I start the work on my forked version of the repository.

**Comment by andreastt** [comment]
No. Additional processing steps is unnecessary for the simplicity of what we are doing here.

**Comment by ddavison** [comment]
this has been discussed several times, and the consensus was that we don't want a server at all

#72
