### ISSUE TITLE
Performance testing software suggestions should be included

### ISSUE THREAD

**Issue by jfisher446** [SeleniumHQ/docs#129]
The [Worst Practices page](../blob/gh-pages/worst.html) has an empty section to add some open source performance testing recommendations. These should be identified and added.

**Comment by diemol** [comment]
@jfisher446 would you like to give us a hand a send a PR?

**Comment by diemol** [comment]
Fixed on new site, please head to https://github.com/SeleniumHQ/seleniumhq.github.io and raise a PR ther if needed.
