### ISSUE TITLE
"Working with Select elements" does not display correctly in the main TOC

### ISSUE THREAD

**Issue by jfisher446** [SeleniumHQ/docs#130]
The link should include the entire section title. Currently, instead of linking with the text "Working with Select elements", it says only "Working with".

**Comment by maeriens** [comment]
This was fixed prior my PR (https://github.com/SeleniumHQ/docs/pull/135, which I incorrectly labeled #129 as I thought it was this ticket) but I fixed the redirections of the table.

**Comment by andreastt** [comment]
OK, marking as closed.
