### ISSUE TITLE
Update Selenium version number automatically

### ISSUE THREAD

**Issue by hazmeister** [SeleniumHQ/docs#147]
As version numbers change from time to time, it would be handy if we replaced the version number in example pom files and jars with the latest version number automatically.  Do we have an endpoint that would work for this purpose?  Something like http://selenium-release.storage.googleapis.com/latest.html ?

Alternatively we could add a class to the current download page, and do an GET request and scrape the latest version number off of the page and add it to a cookie, but that seems kind of hacky.  Any opinions?

**Comment by shs96c** [comment]
Rather than making an HTTP request, we could just have a constant declared somewhere and use that. Of course, it should be bourne in mind that the version numbers of each driver can increment independently (eg. for 3.5, Java got to 3.5.3, but not much else needed to do that many releases)

**Comment by hazmeister** [comment]
That's a good point- PR on the way.

**Comment by diemol** [comment]
@hazmeister if you are still up to give us a hand, please head to https://github.com/SeleniumHQ/seleniumhq.github.io and raise a PR.
