### ISSUE TITLE
Referring to Sleneium Conference link homepage is throwing DNS Resolution Error.

### ISSUE THREAD

**Issue by Ravichandra-C** [SeleniumHQ/docs#148]
Steps to reproduce:
1.Load the https://seleniumhq.github.io/docs/index.html Url
2. Click on the Annual conference link.
![image](https://user-images.githubusercontent.com/17808008/31587550-57224f40-b201-11e7-8080-e9f7bf680fdc.png)
3.below page is shown to the user.

![image](https://user-images.githubusercontent.com/17808008/31587561-8381eeba-b201-11e7-91a7-a19571762faf.png)

**Comment by lukeis** [comment]
@tourdedave looks like dns is messed up a bit for "www.seleniumconf.org" (it works with the naked domain seleniumconf.org)
