### ISSUE TITLE
design issue (layout) 

### ISSUE THREAD

**Issue by umerwaheed21** [SeleniumHQ/docs#159]
Steps to re-produce this issue:

-  Go to "https://seleniumhq.github.io/docs/guidelines.html#fresh_browser_per_test"/
-  Now go to bottom
-  Last Table of contents "Fresh browser per test " is not showing at the bottom.
![screen shot 2017-11-01 at 4 48 42 am](https://user-images.githubusercontent.com/28952196/32273529-0579dd72-bec0-11e7-986c-c281387c6131.png)

**Comment by diemol** [comment]
Tried to reproduce but could not, perhaps it was fixed in a previous commit.

<img width="1611" alt="image" src="https://user-images.githubusercontent.com/5992658/53689148-63590580-3d4f-11e9-92ab-730c40a9cc54.png">
