### ISSUE TITLE
Command Reference link is not working

### ISSUE THREAD

**Issue by gmalange** [SeleniumHQ/docs#162]
In the third paragraph in this [section](http://www.seleniumhq.org/docs/02_selenium_ide.jsp#selenium-commands-selenese) there is a a link to the [Command Reference](http://release.seleniumhq.org/selenium-core/1.0.1/reference.html). The server referenced (release.seleniumhq.org) is down (it does not respond to pings) so the Selenium command reference is not accessible.

**Comment by maeriens** [comment]
I think this should go in the [SeleniumHQ repo?](https://github.com/SeleniumHQ/www.seleniumhq.org/issues)

Also I think it's tracked here https://github.com/SeleniumHQ/www.seleniumhq.org/issues/129

**Comment by diemol** [comment]
Correct, closing as this belongs to the other repo and it is already tracked there.
