### ISSUE TITLE
When I open a new tab in firefox, driver.get(url) sometimes does not return results.  

### ISSUE THREAD

**Issue by xihangalpha** [SeleniumHQ/docs#174]
I use:
Firefox 52
Selenium 3.8.1
geckodriver 0.16.0
Windows Vista

Code (for example):
ActionChains(driver).key_down(Keys.CONTROL).send_keys("t").key_up(Keys.CONTROL).perform()
driver.switch_to_window(driver.window_handles[-1])
driver.get(url)

Sometimes, Firefox can open new tab, but it stops and can not further navigate to the targeted website. In rest cases, Firefox can perform the task successfully.
What is the problem? Can anyone help?

**Comment by ddavison** [comment]
hi @xihangalpha , 

this is most likely a candidate for our [selenium-users google group](https://groups.google.com/forum/#!forum/selenium-users) or [Slack channel](https://seleniumhq.herokuapp.com).  

closing this issue.
