### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by liushilive** [SeleniumHQ/docs#195]
Would you consider translating this document into multiple languages?

是否考虑将本文档翻译为多国语言？

There are many testers in China who are not good at English.

在中国有很多测试人员英语不好。

**Comment by AutomatedTester** [comment]
We would definitely consider doing this but we need help to do that as we don't have anyone who can do the translations. 

Can you start helping?

**Comment by liushilive** [comment]
I am a teacher and I am very happy to be involved in translation work.

How do I submit a translation vocabulary based on the current document architecture?

**Comment by AutomatedTester** [comment]
Good question. It's not something I have done in the past. I will ask the other core contributors if they have thoughts

**Comment by LinuxSuRen** [comment]
I recommend we use [Hugo](https://gohugo.io) to document. I offer you an example [jenkins-x](https://jenkins-x.io/) which is under me and other contributors maintain. Hugo can support i18n very well. Also, I'd like to contribute the translation work.

**Comment by Odeh76** [comment]
I can start translating as well! I speak Arabic fluently. I'm getting my feet wet with open source and would love to contribute in any way possible. Any beginner friendly contributions sent my way would be immensely appreciated! Or any tips on what to fix and focus on.

**Comment by cambiph** [comment]
I can provide Dutch translation.

**Comment by diemol** [comment]
That'd be great, we are in the process of migrating to Hugo, when we are done, we will post here so people can chime in with translations.

**Comment by cambiph** [comment]
> That'd be great, we are in the process of migrating to Hugo, when we are done, we will post here so people can chime in with translations.

Currently busy translating to Dutch in Hugo, works like a charm.

**Comment by diemol** [comment]
I just added the file structure for Spanish, will add a doc showing how to contribute (including how to add translations), after that, I'll close this issue.

Looking forward to your contribution @cambiph! 
(You could also do a partial contribution, e.g. translate only parts and leave the files ready so other people help in the process - just how I just did for Spanish).

**Comment by cambiph** [comment]
@diemol opened the pull request with what I already had. Didn't find enough time to do the complete translation so as per your suggestion, I pushed what I already have. I'll continue the translation when I have more time on my hands.

**Comment by diemol** [comment]
I'll close this since we have the file structure and we have a doc showing how to contribute.
