### ISSUE TITLE
Index link redirects to en

### ISSUE THREAD

**Issue by imba-tjd** [SeleniumHQ/docs#335]
![图片](https://user-images.githubusercontent.com/24759802/62987645-5cdcc700-be73-11e9-8248-dc2b5f9c16b4.png)

This link is `https://seleniumhq.github.io/docs/site` even when you choose other language. And it will redir to `https://seleniumhq.github.io/docs/site/en/`.

**Comment by diemol** [comment]
Thanks for reporting it @imba-tjd, fixed in the linked commit.
