### ISSUE TITLE
Italic failed when followed by Chinese punctuation.

### ISSUE THREAD

**Issue by imba-tjd** [SeleniumHQ/docs#336]
https://seleniumhq.github.io/docs/site/zh-cn/

![图片](https://user-images.githubusercontent.com/24759802/62987788-10de5200-be74-11e9-91ed-acc1f9a624af.png)

The source code is:

```
Selenium 的核心是 _[WebDriver]({{< ref "/webdriver/_index.md" >}})_，这是一个编写指令集的接口，可以在许多浏览器中互换运行。
这里有一个最简单的说明：
```

compare to en:

```
At the core of Selenium is _[WebDriver]({{< ref "/webdriver/_index.md" >}})_, 
an interface to write instruction sets that can be run interchangeably in many 
browsers. Here is one of the simplest instructions you can make:
```

I think the issue is caused by `，`.

**Comment by diemol** [comment]
Thank you for reporting this @imba-tjd, this will be fixed by #339
