### ISSUE TITLE
Documentation has a broken link

### ISSUE THREAD

**Issue by jariah-holsapple** [SeleniumHQ/docs#386]
A sample nodeconfig file for server version 3.x.x (>= beta4) can be seen at https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json 

"https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json" <- is broken, where can we find the default node web driver for the newest verion?

**Comment by diemol** [comment]
Hi @jariah-holsapple,

What is the url where you see this?

**Comment by jariah-holsapple** [comment]
https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json

**Comment by diemol** [comment]
Just fixed it. Thanks for reporting it.
