### ISSUE TITLE
Invalid link in 02_Getting_Started_with_WebDriver.md

### ISSUE THREAD

**Issue by abotalov** [SeleniumHQ/docs#56]
The link "drivers section" links to 404 page - https://github.com/SeleniumHQ/selenium-docs/blob/master/Different%20Drivers%20and%20Requirements

**Comment by davehunt** [comment]
Which file contains this link? If you can, would you like to submit a pull request to fix this link?

**Comment by abotalov** [comment]
File - 02_Getting_Started_with_WebDriver.md
But I'm not sure what should be a correct location

**Comment by andreastt** [comment]
This is meant to link to the page about driver idiosyncrasies.
