### ISSUE TITLE
Document all maven maven driver dependencies

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [SeleniumHQ/docs#64]
**Note1:** I am not sure if this is the correct repository to create this issue, if it is not please point me to the correct resource.  
**Note 2:** I am a total newbie in using selenium. This is the first time I get my hands into the docs so I will be creating issues regarding anything that I think should be documented for clarity.

In `http://docs.seleniumhq.org/docs/03_webdriver.jsp#chapter03-reference`, more specifically in the "Java" section, there is some dependencies examples in maven:

The below example is pretty intuitive. It is supposed to work as the main dependency for java.

``` xml
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-java</artifactId>
  <version>2.44.0</version>
</dependency>
```

The next dependency though is also pretty clear. It means you should add some kind of "driver" dependency for each browser.

``` xml
<dependency>
  <groupId>com.opera</groupId>
   <artifactId>operadriver</artifactId>
</dependency>
```

The problem is that it should contain not only one example of a driver, but the reference to all supported driver artifacts groupIds and artifactIds. This page is supposed to be the first resource to be viewed by a developer after all.

Why is that? You may be asking.

Well, I could look on maven central for "com.google" groupId and "chromedriver" artifactId, but it wouldnt mean I would get the correct and supported artifact. There are cases where people uploaded artifacts using a package but that wasn't the official version of that artifact, that is why the official docs should mention every supported driver, and if it is already mentioned somewhere, it should mention in this specific section to make it clear which drivers are supported.

**If the artifacts are mentioned elsewhere:** Put the relevant links on this page.
**If the artifacts are not mentioned elsewhere:** Create the artifacts references page and put the relevant links on this page.

I hope this is useful to help the documentation to become better.

(Last note: I am creating an issue instead of a pull request because I believe I don't have enough context of the overall documentation to be able to enhance it in a proper way).

**Comment by FagnerMartinsBrack** [comment]
After reading through I realized not all drivers can be used with maven. Chrome, for instance, should be downloaded directly from the website.

This should be referenced early, probably with a link of how to use each driver at http://docs.seleniumhq.org/docs/03_webdriver.jsp#driver-specifics-and-tradeoffs.

**Comment by andreastt** [comment]
Excellent concerns.  Please open an issue against the Selenium issue tracker.

**Comment by FagnerMartinsBrack** [comment]
https://code.google.com/p/selenium/issues/detail?id=8327&thanks=8327&ts=1419615289
