### ISSUE TITLE
Give example of when WebDriver may not wait to page to load

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [SeleniumHQ/docs#65]
In http://docs.seleniumhq.org/docs/03_webdriver.jsp#fetching-a-page there is:

> Dependent on several factors, including the OS/Browser combination, WebDriver may or may not wait for the page to load. In some circumstances, WebDriver may return control before the page has finished, or even started, loading. To ensure robustness, you need to wait for the element(s) to exist in the page using Explicit and Implicit Waits.

It says it is dependent on several factors and circumstances, but which ones? It would be much better to provide some examples, because the code right above uses `driver.get("http://www.google.com");` without waiting for the elements to exist in the page (except the part after `element.submit();`).

So it means that `driver.get("http://www.google.com");` is not robust enough in the code provided? Why not?

You could add the desired documentation in the `Explicit and Implicit Waits` link, to prevent unnecessary verbosity inside the paragraph. If that's the case you could put a `for more information regarding some factors and circumstances that might make WebDriver return control early, check Explicit and Implicit Waits`.

**Comment by andreastt** [comment]
Please open against Selenium's issue tracker.

**Comment by FagnerMartinsBrack** [comment]
https://code.google.com/p/selenium/issues/detail?id=8330&thanks=8330&ts=1419615453
