### ISSUE TITLE
Confusing explanation regarding cookies

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [SeleniumHQ/docs#66]
In http://docs.seleniumhq.org/docs/03_webdriver.jsp#cookies, it says:

> If you are trying to preset cookies before you start interacting with a site and your homepage is large / takes a while to load an alternative is to find a smaller page on the site, typically the 404 page is small (http://example.com/some404page)

A more concise explanation would be:

> If you are trying to preset cookies before you start interacting with a site and your homepage is large **or it** takes a while to load**,** an alternative is to find a smaller page on the site**. T**ypically the **site's** 404 page **is small enough** (http://example.com/some404page)

**Comment by andreastt** [comment]
Please submit a patch or open an issue against the Selenium issue tracker.

**Comment by FagnerMartinsBrack** [comment]
https://code.google.com/p/selenium/issues/detail?id=8329&thanks=8329&ts=1419615417
