### ISSUE TITLE
Invalid link on Firefox Driver section

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [SeleniumHQ/docs#67]
At http://docs.seleniumhq.org/docs/03_webdriver.jsp#firefox-driver the link:

> (see the source to see which ones)

Is invalid.

**Comment by andreastt** [comment]
Please open against Selenium's issue tracker, or submit a patch.

**Comment by FagnerMartinsBrack** [comment]
https://code.google.com/p/selenium/issues/detail?id=8328&thanks=8328&ts=1419615371
