### ISSUE TITLE
Confusing explanation at Explicit vs Explicit waits

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [SeleniumHQ/docs#68]
At http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits there is this part:

> Waiting is having the automated task execution elapse a certain amount of time before continuing with the next step. You should choose to use Explicit Waits or Implicit Waits. Mixing both will cause unintended consequences, namely waits sleeping for the maximum time even if the element is available or condition is true.

The last part is not clear what it means (highlighted):

> Mixing both will cause unintended consequences, **namely waits sleeping for the maximum time even if the element is available or condition is true**.

It would be much clearer if it is written as:

> Mixing both will cause unintended consequences, **like** sleeping for the maximum time even if the element is available or condition is true.

The warning below may be already saying what the last paragraph sentence means:

> WARNING: Do not mix implicit and explicit waits. Doing so can cause unpredictable wait times. For example setting an implicit wait of 10s and an explicit wait of 15 seconds, could cause a timeout to occur after 20 seconds.

So this change might be unnecessary (the offending paragraph sentence could be removed).

**Comment by andreastt** [comment]
Please file a bug against the Selenium issue tracker.  This repo tracks the new documentation which intends to replace docs.seleniumhq.org eventually.

I'll make this clear in the README.

**Comment by andreastt** [comment]
Addressed concern I mentioned in 52d35ea.

**Comment by FagnerMartinsBrack** [comment]
Please, put the link to the relevant issue tracker in the README and make it clear issues should not be opened here to prevent useless effort. Also, many of the issues I created may be useful for the new documentation ;)

**Comment by FagnerMartinsBrack** [comment]
https://code.google.com/p/selenium/issues/detail?id=8331&thanks=8331&ts=1419615569
