### ISSUE TITLE
"When to use a Selenium Grid"

### ISSUE THREAD

**Issue by ddavison** [SeleniumHQ/docs#70]
Based on a conversation on IRC...

```
[excerpt]
"is there much need for Selenium Grid if you have an api that the front end is tapping into with html/js? it sounds it's for load testing in which case i heard something like jboss is more appropriate?"
...
"oh. if the only two browsers we plan to support are chrome/firefox can you picture any need for it?"
[/excerpt]
```

Might be a nice enhancement to eventually have a section that includes a questionnaire that will help someone decide whether they need a grid.

**Example:**
1. Do you need to run tests on different browsers?
2. Will you need dedicated computers to run the tests?

**Comment by hazmeister** [comment]
3. Will the computer running the tests have a desktop environment?
4. Will the users running the tests have the browsers installed, configured and on the right area of the network?

**Comment by diemol** [comment]
@ddavison @hazmeister would you like to add this to the docs?

**Comment by diemol** [comment]
Fixed on new site, please head to https://github.com/SeleniumHQ/seleniumhq.github.io and raise a PR ther if needed.
