### ISSUE TITLE
Start a new WebDriver for each test = increase hugely the total time for execute all the tests?

### ISSUE THREAD

**Issue by JulienBreton** [SeleniumHQ/docs#71]
In the best practices page there is a paragraph named "Fresh Browser Per Test".
In this paragraph it's explained "at least start a new WebDriver for each test".
If a new WebDriver is started after each test, few seconds (maybe 20 or 30 seconds) will be used for start the browser and quit the browser. This process increases hugely the time necessary to execute all the tests.
I understand the interest to start a fresh browser for each tests but the total time necessary for execute all the tests will hugely increase. am I wrong?

Thanks.

**Comment by ddavison** [comment]
If starting up each test takes 20-30 seconds, then you have a bigger problem.  It takes about 3 seconds (max) to bring a browser up (for me, even on crappy t1.micro ec2 instances)

> ...start a fresh browser for each test but the total time necessary for execute all the tests will hugely increase.

Like i said about the time, sure - it will take longer, but it won't be long at all.  And it's up to you whether or not that is worth taking that time to start a new fresh browser, or potentially having your browser in an "unclean state" with cookies and possible session data sticking to that WebDriver instance, which could potentially bring up false-positives in subsequent tests

**Comment by JulienBreton** [comment]
Thanks for the explanations.

Yes, I exaggerated a little :-). It's because I counted the time necessary for login on the Web app. Of course it's independent of Selenium.
When the tests are run in local, on my own computer, starting a test takes less than 3 seconds. Normally the tests are run by Jenkins on a Windows VM, and in this case I count about 8 seconds before I can see the browser. Maybe it's due to network or the VM. I should search in this way.

After all, I will restart the browser after each tests. I prefer a good execution of the tests.

**Comment by lukeis** [comment]
Another tenant is to not perform the login through the UI. For example on my site we can make a REST API connect to get a sessionId and then set that in a cookie to then be able to directly navigate to the page under test. 

Going to close this issue now :)
