### ISSUE TITLE
Migrate docs to build with Jekyll

### ISSUE THREAD

**Issue by btulchinsky** [SeleniumHQ/docs#72]
Would be nice to migrate the docs to using Jekyll. It will allow non-technical users to be able to contribute to the docs and will reduce the reliance on javascript, which will improve page loading, and also enable viewing when javascript is disabled. Also uses liquid for templates.

**Comment by ddavison** [comment]
I love the idea of Jekyll.  I use that for my blog, as well as other "quick sites" I want to spin up.

IIRC though, @andreastt and a few others were against this because of adding an extra build step?  am I correct?

**Comment by btulchinsky** [comment]
If it's hosted through github there is no extra build step. However, there will be an extra step if it's deployed elsewhere.

**Comment by andreastt** [comment]
@btulchinsky What exact benefits will this give us?

My own opinion is that people are eager to offer advice on what technologies they’d like to use, but that this generally translates into very little content actually written.

It’s not my intention to sound snarky here, but I’d rather we focus on writing new content and get the docs into a publishable state.  That’s the only metric of success; not how the documents are edited.
