### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ddavison** [SeleniumHQ/docs#74]
this should be on the page somewhere (probaby the header)

**Comment by Viral1010** [comment]
I think Selenium Logo needs to be redesigned. We wanted to contribute something. Do I have the permission?

**Comment by andreastt** [comment]
@Viral1010 You don’t need permission to suggest something.

**Comment by ddavison** [comment]
@Viral1010 go right ahead!  this is an open source project 👍

**Comment by AJ-72** [comment]
@ddavison where should I add the logo? I was looking for the html source for <header>Selenium Documentation</header> but couldn't find any. How is that being loaded? Same with TOC.

**Comment by manoj9788** [comment]
@AJ-72 Apparently it should be the [index.html](https://github.com/SeleniumHQ/docs/blob/gh-pages/index.html)

**Comment by manoj9788** [comment]
Adding the existing logo should be fine, but redesigning it  - I think we might need some sort of approvals from the SFC @shs96c - thoughts?

**Comment by AJ-72** [comment]
I was thinking of adding the existing only.

**Comment by AJ-72** [comment]
I don't see the header in the index.html. I can see the HTML contents only while inspecting the element. Is it loaded through some other way? This is the code am looking for
`<header><h1>Selenium Documentation</h1></header>`

**Comment by manoj9788** [comment]
That's from the [docs.js ](https://github.com/SeleniumHQ/docs/blob/gh-pages/docs.js#L87)

**Comment by diemol** [comment]
Closing as fixed after implementing the new docs UI powered by [Hugo](https://gohugo.io/)
