### ISSUE TITLE
Show code examples only in one language

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/docs#81]
We want the code examples in the documentation to be available in multiple languages. If we annotate the containers for the code with the language we can implement a folding technique similar to the one found in the existing, official Selenium documentation.

Suggestion for annotation:

``` html
<pre class=py><code>…</code></pre>
<pre class=js><code>…</code></pre>
…
```

This entails writing a bit of JavaScript code to do the language selection, and some CSS to do the styling and folding of the containers.

**Comment by diemol** [comment]
Closed via #175
