### ISSUE TITLE
Code syntax hightlighting

### ISSUE THREAD

**Issue by tommywo** [SeleniumHQ/docs#86]
Code would be a much more readable if syntax was highlighted.

f.ex 
http://prismjs.com/
https://highlightjs.org/
could be used

**Comment by tommywo** [comment]
I gave prismjs a try. It looks pretty good
https://tommywo.github.io/selenium-docs/

**Comment by ddavison** [comment]
a pull request would be greatly appreciated! 👍

**Comment by ghost** [comment]
Hi All,

I noticed it might be better to follow existing html/js logic and just make the change in one doc.js. A new pull request #88  is created for your review. Hope it helps.

**Comment by tommywo** [comment]
@yang458567 nice! thanks
